source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target :SugoDemo do
    pod 'sugo-objc-sdk', :git => 'https://github.com/Datafruit/sugo-objc-sdk.git', :branch => 'release-infinitus'
end
